// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UberGenius.Api.Data;

#nullable disable

namespace UberGenius.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730183704_ConsolidateCancellationFeeColumn")]
    partial class ConsolidateCancellationFeeColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UberGenius.Api.Data.AppAnalyticsEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDriverOnline")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<double?>("SpeedGps")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AppAnalyticsEvents");
                });

            modelBuilder.Entity("UberGenius.Api.Data.DriverProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActiveSince")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DriversUnderPartner")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FleetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsPartner")
                        .HasColumnType("bit");

                    b.Property<string>("LanguagePreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LifetimeCompletedTrips")
                        .HasColumnType("int");

                    b.Property<string>("OperatingCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OptedInToEmail")
                        .HasColumnType("bit");

                    b.Property<bool?>("OptedInToSms")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredLanguageScript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("ReferralCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignupCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SignupDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DriverProfiles");
                });

            modelBuilder.Entity("UberGenius.Api.Data.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CancellationFee")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DistanceMiles")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<double?>("DropoffLatitude")
                        .HasColumnType("float");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DropoffLongitude")
                        .HasColumnType("float");

                    b.Property<decimal?>("Earnings")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<double?>("EarningsMatchDeltaMinutes")
                        .HasColumnType("float");

                    b.Property<string>("EarningsMatchQuality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FareDistanceMiles")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("MatchedPaymentTripUuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PickupLatitude")
                        .HasColumnType("float");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PickupLongitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("RequestedTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("UberGenius.Api.Data.TripPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LocalAmount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTime>("LocalTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MatchedTripId")
                        .HasColumnType("int");

                    b.Property<string>("TripUuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchedTripId");

                    b.ToTable("TripPayments");
                });

            modelBuilder.Entity("UberGenius.Api.Data.TripPayment", b =>
                {
                    b.HasOne("UberGenius.Api.Data.Trip", "MatchedTrip")
                        .WithMany("Payments")
                        .HasForeignKey("MatchedTripId");

                    b.Navigation("MatchedTrip");
                });

            modelBuilder.Entity("UberGenius.Api.Data.Trip", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
